DROP DATABASE IF EXISTS `LIBRARY`;
CREATE DATABASE `LIBRARY`;
USE `LIBRARY`;

CREATE TABLE `users` (
    username NVARCHAR(128) PRIMARY KEY,
    password NVARCHAR(128) NOT NULL
);

CREATE TABLE `authorities` (
	username NVARCHAR(128) NOT NULL,
    authority NVARCHAR(128) NOT NULL
);

ALTER TABLE `authorities` ADD CONSTRAINT `authorities_unique` UNIQUE (USERNAME, AUTHORITY);
ALTER TABLE `authorities` ADD CONSTRAINT `authorities_fk1` FOREIGN KEY (USERNAME) REFERENCES `users` (USERNAME);

CREATE TABLE `books` (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    bd_id INT NOT NULL,
    state CHAR(1)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;
