DROP DATABASE IF EXISTS `LIBRARY`;
CREATE DATABASE `LIBRARY`;
USE `LIBRARY`;

CREATE TABLE `users` (
USERNAME NVARCHAR(128) PRIMARY KEY,
PASSWORD NVARCHAR(128) NOT NULL
);

CREATE TABLE `authorities` (
	USERNAME NVARCHAR(128) NOT NULL,
    AUTHORITY NVARCHAR(128) NOT NULL
);
ALTER TABLE `authorities` ADD CONSTRAINT `authorities_unique` UNIQUE (USERNAME, AUTHORITY);
ALTER TABLE `authorities` ADD CONSTRAINT `authorities_fk1` FOREIGN KEY (USERNAME) REFERENCES `users` (USERNAME);
